version: 2

models:
  - name: dim_location
    description: "Unique geographic locations parsed from stg_customers.location (Country/State/City)."
    columns:
      - name: location_id
        description: "Deterministic MD5 hex hash of (country|state_or_region|city)."
        tests:
          - not_null
          - unique
      - name: country
        description: "Uppercased country name parsed from location."
        tests:
          - not_null
      - name: state_or_region
        description: "Uppercased state, province, or region (nullable)."
      - name: city
        description: "Uppercased city (nullable)."
      - name: _loaded_at
        description: "ETL load timestamp."

  - name: dim_customers
    description: "Customer dimension enriched with location surrogate key."
    columns:
      - name: customer_id
        description: "Business key for customer."
        tests:
          - not_null
          - unique
      - name: email
        description: "Customer email (normalized in Silver)."
      - name: first_name
        description: "Customer first name."
      - name: last_name
        description: "Customer last name."
      - name: join_date
        description: "Customer join date."
      - name: reviewer_level
        description: "Reviewer level from source."
      - name: location_id
        description: "Surrogate key to dim_location."
        tests:
          - relationships:
              to: ref('dim_location')
              field: location_id
      - name: _loaded_at
        description: "ETL load timestamp."
        
  - name: dim_products
    description: "Product dimenion table. One row per product_id."
    columns:
      - name: product_id
        description: "Unique product identifier."
        tests: 
          - not_null
          - unique
      - name: product_name
        description: "Official Product name from source."
      - name: brand
        description: "Brand name."
      - name: category
        description: "Product category."
      - name: price
        description: "Latest known prce in numeric format."
      - name: launch_date
        description: "Date product was first launched or made available."

  - name: dim_date
    description: "Date dimension where date are generated from a start_date = 2024-01-01 to current_date."
    columns:
      - name: date_id
        description: "unique id for each generated date."
        tests:
          - unique
          - not_null
      - name: date_day
        description: "Unique date with start_date of '2024-01-01' to current_date."
        tests:
          - unique
          - not_null
      - name: year
        description: "The year part of the date."
      - name: month
        description: "The month part of the date."
      - name: quarter
        description: "The quarter part of the date."
      - name: day_of_week
        description: "The day of the week for each date"
      - name: week_of_year
        description: "The week of the year for each date."

  - name: fact_reviews
    description: "Reviews fact enriched with relationship with products, customers and date dimension."
    columns:
      - name: review_id
        description: "Unique id for each review."
        tests:
          - unique
          - not_null
      - name: product_id
        description: "product id that links the fact_review to dim_product."
        tests:
           - relationships:
              to: ref('dim_products')
              field: product_id
      - name: customer_id
        description: "customer id that links the fact_reviews to dim_customers."
        tests:
          - relationships:
              to: ref('dim_customers')
              field: customer_id
      - name: date_id
        description: 'data id that links the fact_reviews to dim_date.'
        tests:
         - relationships:
            to: ref('dim_date')
            field: date_id
      - name: review_title
        description: "The unique title to each review."
      - name: review_date
        description: "Date for which each review came in."
      - name: rating
        description: "rating for each reviews."
      - name: total_votes
        description: "The total votes for a particular review."
      - name: helpful_votes
        description: "The number of helpful vote for each review."
      - name: sentiment_score
        description: "The calculated sentiment score for a review."
      - name: verified_purchase
        description: "A boolean to record if a purchase is verified or not"

          
