version: 2

models:
  - name: dim_location
    description: "Unique geographic locations parsed from stg_customers.location (Country/State/City)."
    columns:
      - name: location_id
        description: "Deterministic MD5 hex hash of (country|state_or_region|city)."
        tests:
          - not_null
          - unique
      - name: country
        description: "Uppercased country name parsed from location."
        tests:
          - not_null
      - name: state_or_region
        description: "Uppercased state, province, or region (nullable)."
      - name: city
        description: "Uppercased city (nullable)."
      - name: _loaded_at
        description: "ETL load timestamp."

  - name: dim_customers
    description: "Customer dimension enriched with location surrogate key."
    columns:
      - name: customer_id
        description: "Business key for customer."
        tests:
          - not_null
          - unique
      - name: email
        description: "Customer email (normalized in Silver)."
      - name: first_name
        description: "Customer first name."
      - name: last_name
        description: "Customer last name."
      - name: join_date
        description: "Customer join date."
      - name: reviewer_level
        description: "Reviewer level from source."
      - name: location_id
        description: "Surrogate key to dim_location."
        tests:
          - relationships:
              to: ref('dim_location')
              field: location_id
      - name: _loaded_at
        description: "ETL load timestamp."
        
  - name: dim_products
    description: "Product dimenion table. One row per product_id."
    columns:
      - name: product_id
        description: "Unique product identifier."
        tests: 
          - not_null
          - unique
      - name: product_name
        description: "Official Product name from source."
      - name: brand
        description: "Brand name."
      - name: category
        description: "Product category."
      - name: price
        description: "Latest known price in numeric format."
      - name: launch_date
        description: "Date product was first launched or made available."

  - name: dim_review_analytics
    description: "Aggregated review metrics per product. One row per product_id. This model aggregates multiple records from the silver layer if present,ensuring exactly one record per product_id with summed counts and weighted averages."
    columns:
      - name: product_id
        description: "Product identifier (foreign key to dim_product.product_id)."
        tests:
          - not_null
          - relationships:
              field: product_id
              to: ref('dim_products')
      - name: total_reviews
        description: "Total number of reviews for the product."
      - name: average_rating
        description: "Average rating across all reviews."
      - name: five_star
        description: "Count of 5-star reviews"
      - name: four_star
        description: "Count of 4-star reviews"
      - name: three_star
        description: "Count of 3-star reviews"
      - name: two_star
        description: "Count of 2-star reviews"
      - name: one_star
        description: "Count of 1-star reviews"
      - name: average_sentiment
        description: "Average sentiment score"

