version: 2

models:
  - name: stg_customers
    description: "Cleaned customer records staging model."
    columns:
      - name: customer_id
        description: "Unique customer identifier."
        tests:
          - not_null
          - unique
      - name: email
        description: "Customer email, normalized to lowercase."
        tests:
          - not_null
      - name: first_name
        description: "Customer first name, in proper case."
      - name: last_name
        description: "Customer last name, in proper case."
      - name: join_date
        description: "Date the customer joined."
      - name: location
        description: "Customer’s location."
      - name: reviewer_level
        description: "Customer reviewer level indicator."
      - name: _loaded_at
        description: "Timestamp when record was loaded into Silver layer."

  - name: stg_products
    description: "Cleansed product records staging model."
    columns:
      - name: product_id
        description: "Unque product identifier."
        tests:
          - not_null
          - unique
      - name: product_name
        description: "Product name in proper case."
        tests:
          - not_null
      - name: brand
        description: "Product brand in proper case."
      - name: category
        description: 'Product category in proper case.'
      - name: price
        description: "Price of product in two decimal place."
      - name: launch_date
        description: "Date the product was launched."
      - name: total_review
        description: "Product total review at launched date."
      - name: average_rating
        description: "Product average rating at launched date."
      - name: _loaded_at
        description: "Timestamp when record was loaded into the silver layer."